# Generated by Django 2.2.3 on 2021-01-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dep',
            name='is_super',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=150),
        ),
    ]
