# Generated by Django 2.2.3 on 2021-02-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210204_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='account.Dep', to_field='name'),
        ),
    ]
