# Generated by Django 2.2.3 on 2021-01-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20210127_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('stage', models.CharField(default=0, max_length=128)),
                ('num', models.CharField(max_length=150)),
                ('note', models.CharField(max_length=200)),
                ('is_display', models.BooleanField(default=True)),
                ('birthday', models.CharField(max_length=50)),
                ('is_borrow', models.BooleanField()),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.PhoneDep')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('test', models.CharField(max_length=200)),
                ('is_normal', models.BooleanField()),
                ('note', models.CharField(max_length=200)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.Phone')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
            ],
        ),
    ]
