# Generated by Django 2.2.3 on 2021-02-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20210127_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='dep',
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='phone.PhoneDep'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow', to='phone.Phone'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow', to='account.User'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='account.User'),
        ),
    ]
