# Generated by Django 2.2.3 on 2021-02-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_auto_20210209_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='account.User'),
        ),
    ]
